[package]
name = "http-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "http"
path = "src/http.rs"

[dependencies]
crossbeam = { version = "0.8", optional = true }

[features]
build-crossbeam = ["crossbeam"]

[[bin]]
name = "crossbeam-http-server"
crossbeam = ["build-crossbeam"]
path = "./src/crossbeam-http-server/main.rs"
